#!/bin bash

APP_DIR=/app
TARGET_DIR=${APP_DIR}/Soft

HMMER_VERSION=3.4
HMMER_DIR=${TARGET_DIR}/hmmer-${HMMER_VERSION}
./install-hmmer.sh ${HMMER_VERSION} ${HMMER_DIR}


BLAST_VERSION=2.16.0
BLAST_DIR=${TARGET_DIR}/blast-${BLAST_VERSION}
./install-blast.sh ${BLAST_VERSION} ${BLAST_DIR}

#0.4.0
RPSBPROC_VERSION=$4


MAFFT_VERSION=7.487
MAFFT_DIR=${TARGET_DIR}/mafft-${MAFFT_VERSION}
./install-mafft.sh ${MAFFT_VERSION} ${MAFFT_DIR}

MEGA_VERSION=11.0.13-1
MEGA_DIR=${TARGET_DIR}/mega-${MEGA_VERSION}
install-mega.sh ${MEGA_VERSION} ${MEGA_DIR}
